import audit from "../lib/db/derivedtables/microcontroller-usb-audit.json"

export const generateMicrocontrollerUsbMigration = (): string => {
  const quote = (value: string) => `'${value.replaceAll("'", "''")}'`
  return [
    "-- Generated by bun scripts/generate-microcontroller-usb-migration.ts",
    "-- Manufacturer evidence: docs/microcontroller-usb-audit.md and",
    "-- lib/db/derivedtables/microcontroller-usb-audit.json (2026-09-24).",
    "-- Exact part matches; only has_usb changes. Safe to run repeatedly.",
    ...audit.map(
      (row) =>
        `UPDATE microcontroller SET has_usb = ${Number(row.has_usb)} WHERE UPPER(TRIM(mfr)) = ${quote(row.mfr)};`,
    ),
    "",
  ].join("\n")
}

if (import.meta.main) {
  await Bun.write(
    new URL(
      "../cf-proxy/migrations/0011_microcontroller_usb.sql",
      import.meta.url,
    ),
    generateMicrocontrollerUsbMigration(),
  )
}
