import audit from "../lib/db/derivedtables/microcontroller-usb-audit.json"
import next200 from "../lib/db/derivedtables/microcontroller-usb-audit-next200.json"
import next700 from "../lib/db/derivedtables/microcontroller-usb-audit-next700.json"

export const generateMicrocontrollerUsbMigration = (
  batch: "top100" | "next200" | "next700" = "top100",
): string => {
  const suffix = batch === "top100" ? "" : `-${batch}`
  const rows = { top100: audit, next200, next700 }[batch]
  const quote = (value: string) => `'${value.replaceAll("'", "''")}'`
  return [
    "-- Generated by bun scripts/generate-microcontroller-usb-migration.ts",
    `-- Manufacturer evidence: docs/microcontroller-usb-audit${suffix}.md and`,
    `-- lib/db/derivedtables/microcontroller-usb-audit${suffix}.json (2026-09-24).`,
    "-- Exact part matches; only has_usb changes. Safe to run repeatedly.",
    ...rows.map(
      (row) =>
        `UPDATE microcontroller SET has_usb = ${Number(row.has_usb)} WHERE UPPER(TRIM(mfr)) = ${quote(row.mfr.trim().toUpperCase())};`,
    ),
    "",
  ].join("\n")
}

if (import.meta.main) {
  const batch = process.argv.includes("--next700")
    ? "next700"
    : process.argv.includes("--next200")
      ? "next200"
      : "top100"
  await Bun.write(
    new URL(
      batch === "next700"
        ? "../cf-proxy/migrations/0013_microcontroller_usb_next700.sql"
        : batch === "next200"
          ? "../cf-proxy/migrations/0012_microcontroller_usb_next200.sql"
          : "../cf-proxy/migrations/0011_microcontroller_usb.sql",
      import.meta.url,
    ),
    generateMicrocontrollerUsbMigration(batch),
  )
}
