/**
 * Update the extended_promotional column in the components table.
 *
 * This script reads LCSC codes from a file (one per line, format "C1234")
 * and sets extended_promotional=1 for those components in the database.
 * All other components get extended_promotional=0.
 *
 * The LCSC codes file is generated by scripts/pull-extended-promotional.ts
 * which fetches the list from the JLCPCB API.
 *
 * Usage:
 *   bun run scripts/pull-extended-promotional.ts > extended_promotional_codes.txt
 *   bun run scripts/update-extended-promotional.ts extended_promotional_codes.txt
 *
 * Or pipe directly:
 *   bun run scripts/pull-extended-promotional.ts | bun run scripts/update-extended-promotional.ts -
 */

import { readFileSync } from "node:fs"
import { getDbClient } from "lib/db/get-db-client"

async function main() {
  const inputFile = process.argv[2]
  if (!inputFile) {
    console.error(
      "Usage: bun run scripts/update-extended-promotional.ts <codes-file|->",
    )
    console.error(
      "  Provide '-' to read from stdin, or a filename with LCSC codes (one per line)",
    )
    process.exit(1)
  }

  // Read LCSC codes from file or stdin
  let codesText: string
  if (inputFile === "-") {
    codesText = await new Response(Bun.stdin).text()
  } else {
    codesText = readFileSync(inputFile, "utf-8")
  }

  // Parse LCSC codes: strip "C" prefix and convert to numbers
  const codes = codesText
    .trim()
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .map((code) => {
      const numStr = code.startsWith("C") ? code.slice(1) : code
      const num = parseInt(numStr, 10)
      if (isNaN(num)) {
        console.error(`Warning: skipping invalid LCSC code "${code}"`)
        return null
      }
      return num
    })
    .filter((n): n is number => n !== null)

  console.error(`Loaded ${codes.length} extended promotional LCSC codes`)

  if (codes.length === 0) {
    console.error(
      "ERROR: No extended promotional codes found. " +
        "This likely means the data source is unavailable or changed. " +
        "Refusing to update database with empty data.",
    )
    process.exit(1)
  }

  const db = getDbClient()
  const resetAll =
    process.env.JLCSEARCH_EXTENDED_PROMO_RESET_ALL === "true" ||
    process.argv.includes("--reset-all")

  try {
    if (resetAll) {
      // Resetting the entire table can be expensive. It's useful when updating an
      // existing DB where the promotional set may have changed.
      await db
        .updateTable("components")
        .set({ extended_promotional: 0 })
        .execute()
      console.error("Reset all extended_promotional to 0")
    } else {
      console.error(
        "Skipping full-table reset (set JLCSEARCH_EXTENDED_PROMO_RESET_ALL=true or pass --reset-all to enable).",
      )
    }

    // Then, set extended_promotional=1 for the codes we found
    // Process in batches of 500 to avoid SQL query size limits
    const BATCH_SIZE = 500
    let updatedTotal = 0

    for (let i = 0; i < codes.length; i += BATCH_SIZE) {
      const batch = codes.slice(i, i + BATCH_SIZE)
      const result = await db
        .updateTable("components")
        .set({ extended_promotional: 1 })
        .where("lcsc", "in", batch)
        .executeTakeFirst()

      const updated = Number(result.numUpdatedRows ?? 0)
      updatedTotal += updated
      console.error(
        `  Batch ${Math.floor(i / BATCH_SIZE) + 1}: updated ${updated} rows`,
      )
    }

    console.error(
      `\nDone! Updated ${updatedTotal} components to extended_promotional=1 ` +
        `(out of ${codes.length} codes provided)`,
    )

    // Verify
    const totalExtended = await db
      .selectFrom("components")
      .select(db.fn.countAll().as("count"))
      .where("extended_promotional", "=", 1)
      .executeTakeFirst()

    console.error(
      `Verification: ${totalExtended?.count} components have extended_promotional=1`,
    )
  } finally {
    await db.destroy()
  }
}

main().catch((err) => {
  console.error("Error:", err)
  process.exit(1)
})
