import { Database } from "bun:sqlite"

const db = new Database("db.sqlite3", { readonly: true })
try {
  // The public list is capped at 100 rows; compare the highest-stock records.
  const expected = db
    .query<{ lcsc: number; stock: number; mfr: string }, []>(
      "SELECT lcsc, stock, mfr FROM ethernet_controller WHERE stock > 0 ORDER BY stock DESC LIMIT 100",
    )
    .all()
  if (!expected.length)
    throw new Error("No prepared Ethernet controller stock to verify")
  for (const part of ["W5500", "ENC28J60"]) {
    if (!expected.some((row) => row.mfr.startsWith(part))) {
      throw new Error(`Missing live ${part} in prepared Ethernet controllers`)
    }
  }
  const base = "https://jlcsearch.tscircuit.com/ethernet_controllers/list"
  // The D1 workflow token cannot enumerate/delete remote KV. Refresh the URLs
  // generated by the Ethernet controller form through the site's supported cachebust mechanism.
  const packages = db
    .query<{ value: string }, []>(
      "SELECT DISTINCT package AS value FROM ethernet_controller WHERE package IS NOT NULL",
    )
    .all()
    .map((row) => row.value)
  const queries = new Set([""])
  for (const packageValue of ["", ...packages]) {
    queries.add(new URLSearchParams({ package: packageValue }).toString())
  }
  for (const query of queries) {
    for (const extension of ["", ".json"]) {
      const url = new URL(base + extension)
      url.search = query
      url.searchParams.set("cachebust", "1")
      const response = await fetch(url)
      await response.text()
      if (!response.ok)
        throw new Error(
          `Ethernet controller cache refresh HTTP ${response.status}`,
        )
    }
  }
  for (const suffix of [".json?cachebust=1", ".json"]) {
    const response = await fetch(base + suffix)
    if (!response.ok)
      throw new Error(`Ethernet controller API HTTP ${response.status}`)
    const body: any = await response.json()
    for (const row of expected) {
      const actual = body.ethernet_controllers?.find(
        (c: any) => c.lcsc === row.lcsc,
      )
      if (!actual || actual.stock !== row.stock) {
        throw new Error(
          `Ethernet controller API missing current stock for C${row.lcsc}`,
        )
      }
    }
  }
  for (const suffix of ["?cachebust=1", ""]) {
    const response = await fetch(base + suffix)
    const html = await response.text()
    if (!response.ok || !html.includes(`/C${expected[0].lcsc}`)) {
      throw new Error(
        "Ethernet controller HTML does not contain the highest-stock display",
      )
    }
  }
  console.log(
    `Verified ${expected.length} in-stock Ethernet controllers and refreshed HTML/JSON caches`,
  )
} finally {
  db.close()
}
